server.port: 8080  
spring.profiles.active: dev 
spring.application.name: items
---
spring.profiles: dev 

spring.datasource.driver-class-name: org.hsqldb.jdbc.JDBCDriver
spring.datasource.url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username: sa
spring.datasource.password: sa
spring.jpa.hibernate.ddl-auto: create-drop 

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true 
       
logging.level.org.springframework.data: DEBUG
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
logging.level.com.rock.jpetstore: DEBUG
 
#springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

inventory.server.url: ${inventory-endpoint} 

management.endpoints.web.exposure.include: health,info,prometheus
--- 
spring.profiles: prod

spring.datasource.url: ${db-url}
spring.datasource.username: ${db-username}
spring.datasource.password: ${db-password}
spring.datasource.driver-class-name: ${db-classname}

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false 
       
logging.level.org.springframework.data: ERROR
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: ERROR
logging.level.org.springframework.jdbc.core.JdbcTemplate: ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: ERROR
logging.level.com.rock.jpetstore: ERROR

#springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

management.endpoints.web.exposure.include: health,info,prometheus